# Generated by Django 5.1.4 on 2025-04-30 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Отображаемое имя пункта меню', max_length=255, verbose_name='Название пункта')),
                ('slug', models.SlugField(help_text='Уникальный slug идентификатор', unique=True, verbose_name='Слаг')),
                ('menu_name', models.CharField(db_index=True, help_text='Служебное имя меню, например: main_menu', max_length=100, verbose_name='Название меню')),
                ('named_url', models.CharField(blank=True, help_text='Имя маршрута в urls.py (если используется)', max_length=255, null=True, verbose_name='Named URL')),
                ('custom_url', models.CharField(blank=True, help_text='Прямой URL (например, https://site.com/page/)', max_length=255, null=True, verbose_name='Пользовательский URL')),
                ('parent', models.ForeignKey(blank=True, help_text='Если указать — пункт станет дочерним', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['id'],
            },
        ),
    ]
